### ISSUE TITLE
I need some help here

### ISSUE THREAD

**Issue by Maxino22** [stangatimu/lipa-na-mpesa-api#2]
This is kinda my first time using the  mpesa api with flask... i followed the outlined code to step but i'm getting bad request errors... i would like your assistance on the part where we are using base64... I would like to know why we are encoding this and also the fomat in which we are suplying this values since it  is one string...

![for_github](https://user-images.githubusercontent.com/67841055/154134768-674402e7-80fb-4853-8c2d-bfc818b64a6f.png)

Also datetime module was imported but not used i was assuming this would help us get the currenttime stamp and finally am confused about the callback url .. Kindly assist

**Comment by stangatimu** [comment]
Hello max, we encode the Bussiness shortcode+online passkey+ current timestamp (yyyyMMhhmmss) to a base64 string to make up the `Password` field for the request payload since that was a required field by Daraja API at the time making of this tutorial. The `encoded_data` variable is hardcoded for the purposes of the tutorial. You have to use defined variables to make up the string and that's where the `datetime` import would be used to get the current timestamp.
I hope this helps 🙂

**Comment by Maxino22** [comment]
Thanks this actually helped a lot now just the callback url is what i do not understand ... does it need to be live or something

**Comment by stangatimu** [comment]
Yes the callback URL needs to be a live endpoint that the Daraja API can call after the payment processing is done, before going live you can use a dummy live endpoint to get a glimpse of both the success and errors responses that come from the Daraja API

**Comment by Maxino22** [comment]
Hello stan Thanks a lot i got it to work.
